### ISSUE TITLE
The Dialogue length of Reinforce

### ISSUE THREAD

**Issue by JasZhanAva** [GuessWhatGame/guesswhat#11]
In reinforcement learning paper, I noticed there is some analysis about dialogue length. 'REINFORCE learns to stop on average after 4:1 questions'. However, I tested the provided model and I also re-train a new RL model, but the question length seems to keep at 5, which is the max question number in the code.

The way I count the question length is to count the stop token (<?>) number in per dialogue and then average them. Basically, all the dialogue has 5 questions for provided model or myself re-train model. Can you give some explanations about this? I noticed the examples provided in the paper have 2 or 3 questions in some cases.

And also, I'm quite confused about the figure5 in the RL paper. How's the success ratio (blue dot line) behaves like that? And I'm not sure what the axis stands for? Thanks!

**Comment by JasZhanAva** [comment]
And I still confused about the results, in RL paper, RL sampling accuracies are higher than the Github page, and I test myself re-trained model, and it matches the Github page results. So the Github results are the final version after you fixed the bug, right?

**Comment by fstrub95** [comment]
Hi Jace, 
When we first wrote the paper, we did observe REINFORCE to stop after 4.1 tokens. 
Yet, we discover a bug after the conference while releasing the code. From time to time, the final generated questions was not taken into account (stupid index error). This silly bug has actually a dramatical effect.

The final accuracy after RL increased a lot, but some of the initial analysis did not hold anymore. For instance, REINFORCE stop learning to stop... Greedy becomes more efficient than sampling (which is more in line with RL theory). Beam-search is slightly lower than greedy but still perform ok.

This bug did not change the intuition of the paper (using RL vs using Supervised) and the score are better. That is the reason why we did not withdraw the paper. Note that we uploaded the code with the bug fix and put a big warning in the README :) 
If you want to report some results, report the results from the github instead of the results from the paper. 

We have been working on several other projects, so we did not have the time to fix the arxiv paper. Yet, I have two Master students working on it. So sooner or later, the RL paper will be updated with fine results.

Regarding your initial concern: can we reduce teach the QGen to stop asking questions? There is a classic trick in Dialogue systems to do it. Add a negative reward after each question (-0.10 for instance) and the magic will occur :)
To do it, you just need to update the following lines (basic_looper.py):

        # Compute cumulative reward 
        cum_rewards = np.zeros_like(padded_dialogue, dtype=np.float32)
        for i, (end_of_dialogue, r) in enumerate(zip(seq_length, final_reward)):
            cum_rewards[i, :(end_of_dialogue - 1)] = r  # gamma = 1

**Comment by JasZhanAva** [comment]
Thanks for the explanations. I'll try this reward.

**Comment by fstrub95** [comment]
I reoppen the issue as it can be helpful for other people.
