### ISSUE TITLE
about dic.json file

### ISSUE THREAD

**Issue by JasZhanAva** [GuessWhatGame/guesswhat#7]
First of all thanks for releasing the code. I'm trying to reproduce the code, however I think dict file which the pre-train models used is different from the one generated by creat_dictionary.py file. Can you provide the dict.json file you used in the pre-train models? Also, if the <?> is the stop token, why define a stop token separately in line 29(create_dictionary.py file)? Thanks!

**Comment by fstrub95** [comment]
Hi Josh Will,
I updated the pretrained_networks.zip with the dico_file. My bad, I thought
it was included!

Regarding the <stop> token, it is some code legacy that should be removed.
Thx for spotting it, I am going to clean it.

Besides, it turns out that the new tensorflow version break (again...) the
checkpoint for rnn.
Thus, I am going to retrain all the models from scratch with a new dico and
config file soon.

If you have any questions, do not hesitate! I will answer them asap.

Florian

PS the mismatch in dictionary may come from different version of python. Indeed, the dictionary hashing function may differs from one version to another.

**Comment by JasZhanAva** [comment]
Thanks for the quick reply, the dict.json you provide match the pre-train model. Cheers! @fstrub95
