### ISSUE TITLE
Confusion About the Game playing results

### ISSUE THREAD

**Issue by shekharRavi** [GuessWhatGame/guesswhat#9]
Hi, 
 I have some doubt about the baseline results of the game play in GuessWhat [1] , RL [2] and git [3] new results. Let me try to explain the doubt. 
 
- In  GuessWhat[1] paper, Table 4 says, error on the game play with QGen+GT & QGen+ORACLE are 53.2% and 66.0% respectively i.e Accuracy is 46.8% and 34.0% respectively.  (This is using BeamSearch on Test, right?)
-  In  RL [2] paper, Table 2 (results with New Images) Beam search baseline accuracy is 53.0% i.e. 47.0% error. (Here I am assuming the QGen+GT is being used, correct me if wrong). **Result mismatch** from [1], in [1] it is other way around.
- In git [3] results, 2nd last table (results with New Images) says Beam search baseline accuracy (I am assuming it is accuracy, correct me if I am wrong) is 44.6% i.e error is 55.6%.  In [1] error was 53.2%, now in [3] error is 55.6% i.e. increase in error ( **decrease in accuracy**), but on git, you say "New score **greatly increase** the final score reported in [1]". 
- If git [3] results 2nd last table is **Error instead of Accuracy** then baseline error is 44.6% i.e accuracy is 55.6%. Then it is greatly improving result on [1]. But if this is error then this means that **RL is actually performing poorer compare to baseline** because baseline error is 44.6% while RL error is 58.4%.

Please clarify.  

[1] https://arxiv.org/abs/1611.08481. "GuessWhat?! Visual object discovery through multi-modal dialogue" 
[2] https://arxiv.org/abs/1703.05423 . "End-to-end optimization of goal-driven and visually grounded dialogue systems"
[3] https://github.com/GuessWhatGame/guesswhat

**Comment by fstrub95** [comment]
Hi!
Sure, we have been trying several metrics and models. That sometimes makes the baseline (very) confusing.
Please, always refer to the GitHub code for up-to-date scores.
As a rule of thumb, 
Oracle/Guesser are expressed with errors
QGen is expressed with accuracy

Regarding point 1:
In [1], we used QGen error; we used HRED + beam_search
In [3], we used QGen accuracy, with LSTM + beam_search

If we only used accuracy, we then have:
HRED + Beam Search: 46.8% accuracy
LSTM + Beam Search: 44.6% accuracy
Note that HRED is a lot more complex than LSTM. 
For [2], we use LSTM as we wanted to focus on the RL parts and not advanced architectures. Besides, HRED was a lot harder to finetune in our first experiments, so we discard this model in our following works. 

Regarding point 2:
In [2], we used QGen accuracy normalized by the human score (84% success rate). This was an unfortunate choice that was inspired by some AI papers. 
Thus, if you pick 53.0% and you multiply the score by 0.84, you obtain 44,52% accuracy. Thus, it matches GitHub scores.

Regarding point 3:
It turns out that we manage to greatly increase the REINFORCE accuracy of the QGen by fixing a bug. The GitHub pages summarize the updated accuracy.

Regarding point 4:
If you use accuracy, then you would observe that REINFORCE definitly increases the accuracy by more than 10points.

We do apologize for the confusions. Research is a slow process and sometimes, we made some  choices that turn out to be bad 6-8 month after publications. For instance, MS Coco has to completly change its evaluation procedure at some point.

Anyway, something is still unclear! Keep asking question, Harm or I will answer asap.

Florian

**Comment by shekharRavi** [comment]
Hi, 
Thanks a lot for the clarification. Totally understand your point, planning to reproduce the results so wanted to be doubly sure which no. of compare. 
Few more questions :
- Do this new baseline results  (i.e. BeamSearch 44.6%), is based on 5 questions (as in [1]) or model using <stop_dialogue> token (as in [2])
-  what configuration you have used for the Oracle & Guesser while playing the GuessWhat Game. It might be best configuration as in [1], just want to be sure.
- Could you please try to explain bit more about 'New Objects' part, I did not clearly got from paper. By sampling, did you make sure that training & testing object category is mutually exclusive or something else?

One simple suggestion, on git it will be clearer (atleast to me) if you write 'Game Accuracy' (or something similar) instead of 'Detailed scores' . 

Thanks again for taking time to clear things.

**Comment by fstrub95** [comment]
Please find below the answers to your questions:

- The  baseline in github and RL papers accuracy are computed with the <stop_dialogue> tokens. Otherwise, we would have train models with two different probability distributions.

- We used the configuration provided in the github. (It is should be very close to the configuration we used in [1])

- Regarding "New Object", you may want to have a look to this post for further explanation: https://github.com/GuessWhatGame/guesswhat/issues/10

I also fixed the README following your suggestion: 
https://github.com/GuessWhatGame/guesswhat/commit/832cbd8825ad44804a47756844c1a7f87df386d4

Tell us if something is still not clear!

Kind regards, 
Florian

**Comment by shekharRavi** [comment]
Thanks for the clarification.
